### PR TITLE
Fix 'stylelint' error

### PR DESCRIPTION
**Pull request by desmond9319**
Fixed all the `.scss` files which caused `stylelint`error

---
This change is [Reviewable](https://reviewable.io/reviews/cepave-f2e/vue-owl-ui/148)

### CODE REVIEW

**Comment by rwu823** [comment]
Reviewed 1 of 2 files at r1, 1 of 15 files at r2.
Review status: 2 of 16 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/client/views/components/components.scss, line 1 at r2](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/148#-KfKEGDfHJUu4K74_2wc:-KfKEGDfHJUu4K74_2wd:b4bgdeh) ([raw file](https://github.com/cepave-f2e/vue-owl-ui/blob/fff1699d7d956ef33dff6050431ed79293c667f7/src/client/views/components/components.scss#L1)):*
> ```SCSS
> %side-view-margin {
> ```

`%`   @@?      @dsweih 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/148)*

**Comment by rwu823** [comment]
Reviewed 14 of 15 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/148)*

**Comment by rwu823** [comment]
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[src/client/views/components/components.scss, line 1 at r2](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/148#-KfKEGDfHJUu4K74_2wc:-KfKGSjtZ57_1DhB9H7C:bn7zwe2) ([raw file](https://github.com/cepave-f2e/vue-owl-ui/blob/fff1699d7d956ef33dff6050431ed79293c667f7/src/client/views/components/components.scss#L1)):*
<details><summary><i>Previously, rwu823 (Rocky Wu) wrote…</i></summary><blockquote>

`%`   @@?      @dsweih 
</blockquote></details>

學習了!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/148)*

**Comment by rwu823** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/148#-:-KfKGXk_Dqlw4SX_nHyo:bnfp4nl)*

**Comment by rwu823** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[a discussion](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/148#-KfKGj_yC1U4RuH0Q08A:-KfKGj_yC1U4RuH0Q08B:bdmsbue) (no related file):*
Rebase required

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/148)*

**Comment by CApopsicle** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/148#-:-KfKWuVkF3P30swHYHrB:bnfp4nl)*

**Pull request merged**
