### PR TITLE
[0.6.1] Legacy

### PR DESCRIPTION
**Pull request by rwu823**
新增 `Legacy` namespace 用來存放舊有的 Break API Changed 的 Components

image

@CApopsicle

---
This change is [Reviewable](https://reviewable.io/reviews/cepave-f2e/vue-owl-ui/137)

### CODE REVIEW

**Comment by rwu823** [comment]
Reviewed 1 of 10 files at r1.
Review status: 1 of 10 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/client/views/components/index.js, line 19 at r1](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/137#-KdhJzuIxTEy68Wh2LxH:-KdhJzuIxTEy68Wh2LxI:bc0gei3) ([raw file](https://github.com/cepave-f2e/vue-owl-ui/blob/a3cb4d2df89317e722ca4a5816f88279b60d47f4/src/client/views/components/index.js#L19)):*
> ```JavaScript
>                   <Link to="/components/legacy/grid">Grid</Link>
>                 </dd>
>               </dl>
> ```

testing

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/137)*

**Comment by CApopsicle** [comment]
LGTM

---

Review status: 1 of 11 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/137#-:-KdhhF_PBe6xGMBLG9nE:bb6ywmx)*

**Comment by CApopsicle** [comment]
Reviewed 10 of 10 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/137)*

**Comment by rwu823** [comment]
:lgtm: 有圖可用耶 XD

---

Reviewed 1 of 10 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/137#-:-Kdhj6tgZXEIgH0F6iPD:b-me3tkl)*

**Comment by rwu823** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/137#-Kdhjtz7PbGY-y-yTJKw:-Kdhjtz7PbGY-y-yTJKx:bmojs7a) (no related file):*
可以有像 slack 的 thread 功能，在同個 block 進行討論，不會像 github 的 comment 都被打平

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/137)*

**Comment by CApopsicle** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/137#-Kdhjtz7PbGY-y-yTJKw:-KdhkKeOqE-lkiBzN32G:b-3qh5gr) (no related file):*
<details><summary><i>Previously, rwu823 (Rocky Wu) wrote…</i></summary><blockquote>

可以有像 slack 的 thread 功能，在同個 block 進行討論，不會像 github 的 comment 都被打平
</blockquote></details>

這不錯! 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/137)*

**Comment by rwu823** [comment]
Reviewed 8 of 10 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/137)*

**Comment by rwu823** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/client/views/components/index.js, line 19 at r1](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/137#-KdhJzuIxTEy68Wh2LxH:-Kdhlq63fYiP-tIB8m4V:b-896fix) ([raw file](https://github.com/cepave-f2e/vue-owl-ui/blob/a3cb4d2df89317e722ca4a5816f88279b60d47f4/src/client/views/components/index.js#L19)):*
<details><summary><i>Previously, rwu823 (Rocky Wu) wrote…</i></summary><blockquote>

testing
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/137)*

**Pull request merged**
