### PR TITLE
Upgraded packages

### PR DESCRIPTION
**Pull request by rwu823**
- 更新相依套件
- 把 Webpack config 改成 2.0 建議用法
https://webpack.js.org/guides/migrating/#module-loaders-is-now-module-rules
- Separate out `jest.config.json` form `package.json`

### CODE REVIEW

**Comment by CApopsicle** [comment]
WOW文件也更新了 😲 
這邊`vue-owl-ui/webpack/test.js`
跟這邊`vue-owl-ui/webpack/server.js`
的`loaders`也要改成 `use` ?

**Comment by rwu823** [comment]
喔喔對，我一併改 QQ

**Comment by rwu823** [comment]
Fixed.

**Review by CApopsicle — APPROVED** [review]
looks good

**Pull request merged**
