### PR TITLE
[Message] New component feature

### PR DESCRIPTION
**Pull request by desmond9319**
Message component

kapture 2017-04-12 at 18 20 29

- [x] component

- [x] test specs

- [x] document

@rwu823 @CApopsicle

---
This change is [Reviewable](https://reviewable.io/reviews/cepave-f2e/vue-owl-ui/163)

### CODE REVIEW

**Comment by rwu823** [comment]
Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/components/message/index.js, line 100 at r1](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/163#-Khu_YV2V0WLZ93JdYsC:-Khu_YV3B7VvE8lf37IT:bb62ag5) ([raw file](https://github.com/cepave-f2e/vue-owl-ui/blob/7f6bd17381c6156c9985396f29737ff384c56f70/src/components/message/index.js#L100)):*
> ```JavaScript
>           <Icon typ={iconImg[type]} size={40} class={[s.messageIcon, s[type]]} />
>         }
>         <div class={{ [s.messageContent]: true, [s.hasIcon]: iconClass }}>
> ```

這邊如果永遠為 `true` 可以寫成: `<div class={[s.messageContent, { [s.hasIcon]: iconClass}]}></div>` 比較清楚

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/163)*

**Comment by rwu823** [comment]
Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/163)*

**Comment by rwu823** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[src/components/message/index.js, line 70 at r1](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/163#-KhucbIZyKThquMMjLIF:-KhucbIZyKThquMMjLIG:b-17n9gk) ([raw file](https://github.com/cepave-f2e/vue-owl-ui/blob/7f6bd17381c6156c9985396f29737ff384c56f70/src/components/message/index.js#L70)):*
> ```JavaScript
>       }, 300)
> 
>       if (typeof this.onClose === 'function') {
> ```

因為上面 props 已經有限定傳入 `function` 型態了，所以這邊可以單純的判斷有沒有值即可

```js
if (this.onClose)
```

---

*[src/components/message/index.js, line 104 at r1](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/163#-Khub68sshWUnMF-0P5f:-Khub68tWTxOguDYJxpw:bypfx5r) ([raw file](https://github.com/cepave-f2e/vue-owl-ui/blob/7f6bd17381c6156c9985396f29737ff384c56f70/src/components/message/index.js#L104)):*
> ```JavaScript
>             {
>               !!iconClass &&
>               <i class={[s.customIcon, iconClass]}></i>
> ```

沒內容的話，可以 self-close `<i />`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/163)*

**Comment by rwu823** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[src/components/message/message.scss, line 1 at r1](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/163#-Khupmu-qdqQhMJrTdVM:-Khupmu-qdqQhMJrTdVN:b-bxtkx2) ([raw file](https://github.com/cepave-f2e/vue-owl-ui/blob/7f6bd17381c6156c9985396f29737ff384c56f70/src/components/message/message.scss#L1)):*
> ```SCSS
> @import "../global.scss";
> ```

Why import `global` @@?

---

*[src/components/message/message.scss, line 18 at r1](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/163#-KhupwbpolTeaBqy9uH6:-KhupwbpolTeaBqy9uH7:bgg0cgi) ([raw file](https://github.com/cepave-f2e/vue-owl-ui/blob/7f6bd17381c6156c9985396f29737ff384c56f70/src/components/message/message.scss#L18)):*
> ```SCSS
>   border-radius: 2px;
>   background-color: #fff;
>   .messageIcon {
> ```

有 css module，建議用一層 class 就行了

---

*[src/components/message/message.scss, line 25 at r1](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/163#-Khuq1RR0p0OwAkBLvil:-Khuq1RR0p0OwAkBLvim:bgg0cgi) ([raw file](https://github.com/cepave-f2e/vue-owl-ui/blob/7f6bd17381c6156c9985396f29737ff384c56f70/src/components/message/message.scss#L25)):*
> ```SCSS
>     top: 0;
>   }
>   .messageContent {
> ```

有 css module，建議用一層 class 就行了

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/163)*

**Comment by desmond9319** [comment]
*[src/components/message/message.scss, line 1 at r1](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/163#-Khupmu-qdqQhMJrTdVM:-KhutZi8HFVvxzoG0juy:bd9gwmn) ([raw file](https://github.com/cepave-f2e/vue-owl-ui/blob/7f6bd17381c6156c9985396f29737ff384c56f70/src/components/message/message.scss#L1)):*
<details><summary><i>Previously, rwu823 (Rocky Wu) wrote…</i></summary><blockquote>

Why import `global` @@?
</blockquote></details>

To use the color constant `--OWL-UI-COLOR-PRIMARY`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/163)*

**Comment by rwu823** [comment]
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[src/components/message/message.scss, line 1 at r1](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/163#-Khupmu-qdqQhMJrTdVM:-Khuv6AUnkey0x-C0EhF:b-y0jlpl) ([raw file](https://github.com/cepave-f2e/vue-owl-ui/blob/7f6bd17381c6156c9985396f29737ff384c56f70/src/components/message/message.scss#L1)):*
<details><summary><i>Previously, Dsweih (Desmond Hsu) wrote…</i></summary><blockquote>

To use the color constant `--OWL-UI-COLOR-PRIMARY`
</blockquote></details>

試試不 import 看看，我記得 color 已經是 global 的了

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/163)*

**Comment by desmond9319** [comment]
*[src/components/message/index.js, line 70 at r1](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/163#-KhucbIZyKThquMMjLIF:-Khv-vAJ-HnyNElfRnei:b-886gsx) ([raw file](https://github.com/cepave-f2e/vue-owl-ui/blob/7f6bd17381c6156c9985396f29737ff384c56f70/src/components/message/index.js#L70)):*
<details><summary><i>Previously, rwu823 (Rocky Wu) wrote…</i></summary><blockquote>

因為上面 props 已經有限定傳入 `function` 型態了，所以這邊可以單純的判斷有沒有值即可

```js
if (this.onClose)
```
</blockquote></details>

Fixed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/163)*

**Comment by desmond9319** [comment]
*[src/components/message/index.js, line 100 at r1](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/163#-Khu_YV2V0WLZ93JdYsC:-Khv01jEgS7yQEorEVBp:b2zmt0f) ([raw file](https://github.com/cepave-f2e/vue-owl-ui/blob/7f6bd17381c6156c9985396f29737ff384c56f70/src/components/message/index.js#L100)):*
<details><summary><i>Previously, rwu823 (Rocky Wu) wrote…</i></summary><blockquote>

這邊如果永遠為 `true` 可以寫成: `<div class={[s.messageContent, { [s.hasIcon]: iconClass}]}></div>` 比較清楚
</blockquote></details>

了解！

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/163)*

**Comment by desmond9319** [comment]
*[src/components/message/index.js, line 104 at r1](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/163#-Khub68sshWUnMF-0P5f:-Khv076KVSGe_QqEHlQp:bqviv66) ([raw file](https://github.com/cepave-f2e/vue-owl-ui/blob/7f6bd17381c6156c9985396f29737ff384c56f70/src/components/message/index.js#L104)):*
<details><summary><i>Previously, rwu823 (Rocky Wu) wrote…</i></summary><blockquote>

沒內容的話，可以 self-close `<i />`
</blockquote></details>

知道了！

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/163)*

**Comment by desmond9319** [comment]
*[src/components/message/message.scss, line 1 at r1](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/163#-Khupmu-qdqQhMJrTdVM:-Khv3wqp5xGumlCN58Q4:b304lq3) ([raw file](https://github.com/cepave-f2e/vue-owl-ui/blob/7f6bd17381c6156c9985396f29737ff384c56f70/src/components/message/message.scss#L1)):*
<details><summary><i>Previously, rwu823 (Rocky Wu) wrote…</i></summary><blockquote>

試試不 import 看看，我記得 color 已經是 global 的了
</blockquote></details>

可以耶

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/163)*

**Comment by rwu823** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/163)*

**Comment by desmond9319** [comment]
*[src/components/message/message.scss, line 18 at r1](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/163#-KhupwbpolTeaBqy9uH6:-KhvR2moFw483C_J47QU:b-886gsx) ([raw file](https://github.com/cepave-f2e/vue-owl-ui/blob/7f6bd17381c6156c9985396f29737ff384c56f70/src/components/message/message.scss#L18)):*
<details><summary><i>Previously, rwu823 (Rocky Wu) wrote…</i></summary><blockquote>

有 css module，建議用一層 class 就行了
</blockquote></details>

Fixed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/163)*

**Comment by desmond9319** [comment]
*[src/components/message/message.scss, line 25 at r1](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/163#-Khuq1RR0p0OwAkBLvil:-KhvR52SgbYU3GkiPwAJ:b-886gsx) ([raw file](https://github.com/cepave-f2e/vue-owl-ui/blob/7f6bd17381c6156c9985396f29737ff384c56f70/src/components/message/message.scss#L25)):*
<details><summary><i>Previously, rwu823 (Rocky Wu) wrote…</i></summary><blockquote>

有 css module，建議用一層 class 就行了
</blockquote></details>

Fixed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/163)*

**Comment by rwu823** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

*[src/components/message/index.js, line 68 at r2](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/163#-KhvV_5Wo72KpeKKkQ2r:-KhvV_5Wo72KpeKKkQ2s:b-2mpzpx) ([raw file](https://github.com/cepave-f2e/vue-owl-ui/blob/0fa47179dceadfc43ec656a6bbfdfebf6227ab20/src/components/message/index.js#L68)):*
> ```JavaScript
>       setTimeout(() => {
>         this.$destroy()
>       }, 300)
> ```

這邊可以用 `animationend` 來實作，未來如果更改動畫時間，也不用改 code

```js
this.$el.addEventListener('animationend', (ev) => {
  this.$destroy()
}, false)
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/163)*

**Comment by rwu823** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/components/message/message.scss, line 36 at r2](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/163#-KhyxPyVNHQKvbU0OlnN:-KhyxPyVNHQKvbU0OlnO:b7jwews) ([raw file](https://github.com/cepave-f2e/vue-owl-ui/blob/0fa47179dceadfc43ec656a6bbfdfebf6227ab20/src/components/message/message.scss#L36)):*
> ```SCSS
>     color: #8391a5;
>     text-align: justify;
>     .customIcon {
> ```

單層 selector 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/163)*

**Comment by rwu823** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[src/components/message/__test__/message.spec.js, line 23 at r2](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/163#-Khz-My5u69PIUntYL6D:-Khz-My5u69PIUntYL6E:b7834hj) ([raw file](https://github.com/cepave-f2e/vue-owl-ui/blob/0fa47179dceadfc43ec656a6bbfdfebf6227ab20/src/components/message/__test__/message.spec.js#L23)):*
> ```JavaScript
>     if (vm) {
>       vm.$destroy()
>     }
> ```

```js
if (el) {
      el.remove()
}
if (vm) {
      vm.$destroy()
 }
```
這兩個感覺沒有必要一起 @@? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/163)*

**Comment by CApopsicle** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[src/components/message/index.js, line 60 at r2](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/163#-Khz26r4QnIEvwwAjXTI:-Khz26r4QnIEvwwAjXTJ:b-xtine2) ([raw file](https://github.com/cepave-f2e/vue-owl-ui/blob/0fa47179dceadfc43ec656a6bbfdfebf6227ab20/src/components/message/index.js#L60)):*
> ```JavaScript
> 
>   destroyed() {
>     this.$el.remove()
> ```

這邊以前會用 `this.$el.parentNode.removeChild(this.$el)` 
查了一下 `this.$el.remove()` 用的是比較新的寫法
https://www.w3schools.com/js/js_htmldom_nodes.asp
@rwu823 覺得呢

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/163)*

**Comment by desmond9319** [comment]
*[src/components/message/index.js, line 68 at r2](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/163#-KhvV_5Wo72KpeKKkQ2r:-Khz3OKE_x6QGuRv9Z_C:b9ql7mp) ([raw file](https://github.com/cepave-f2e/vue-owl-ui/blob/0fa47179dceadfc43ec656a6bbfdfebf6227ab20/src/components/message/index.js#L68)):*
<details><summary><i>Previously, rwu823 (Rocky Wu) wrote…</i></summary><blockquote>

這邊可以用 `animationend` 來實作，未來如果更改動畫時間，也不用改 code

```js
this.$el.addEventListener('animationend', (ev) => {
  this.$destroy()
}, false)
```

</blockquote></details>

不知道有這個event耶，學習了

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/163)*

**Comment by rwu823** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[src/components/message/index.js, line 60 at r2](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/163#-Khz26r4QnIEvwwAjXTI:-Khz8iffuQ8n7cG61WUW:b-v53pvc) ([raw file](https://github.com/cepave-f2e/vue-owl-ui/blob/0fa47179dceadfc43ec656a6bbfdfebf6227ab20/src/components/message/index.js#L60)):*
<details><summary><i>Previously, CApopsicle (Kelly Su) wrote…</i></summary><blockquote>

這邊以前會用 `this.$el.parentNode.removeChild(this.$el)` 
查了一下 `this.$el.remove()` 用的是比較新的寫法
https://www.w3schools.com/js/js_htmldom_nodes.asp
@rwu823 覺得呢
</blockquote></details>

不能直接用 `this.$destroy()` 嗎 ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/163)*

**Comment by rwu823** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[src/components/message/index.js, line 60 at r2](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/163#-Khz26r4QnIEvwwAjXTI:-Khz9YmLCNChUn1bYPXs:b-8i9k96) ([raw file](https://github.com/cepave-f2e/vue-owl-ui/blob/0fa47179dceadfc43ec656a6bbfdfebf6227ab20/src/components/message/index.js#L60)):*
<details><summary><i>Previously, rwu823 (Rocky Wu) wrote…</i></summary><blockquote>

不能直接用 `this.$destroy()` 嗎 ?
</blockquote></details>

vue 的機制應該會自動移除元素了 @@?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/163)*

**Comment by desmond9319** [comment]
*[src/components/message/index.js, line 60 at r2](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/163#-Khz26r4QnIEvwwAjXTI:-KhzHMFbZOpmVRcqGbWn:b-u393zy) ([raw file](https://github.com/cepave-f2e/vue-owl-ui/blob/0fa47179dceadfc43ec656a6bbfdfebf6227ab20/src/components/message/index.js#L60)):*
<details><summary><i>Previously, rwu823 (Rocky Wu) wrote…</i></summary><blockquote>

vue 的機制應該會自動移除元素了 @@?
</blockquote></details>

this.$destroy() 是移除 vnode
this.$el.remove() 是移除 dom 上的 node

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/163)*

**Comment by CApopsicle** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[src/components/message/index.js, line 68 at r2](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/163#-KhvV_5Wo72KpeKKkQ2r:-KhzHjm99bYzW9pWzorG:b3czpet) ([raw file](https://github.com/cepave-f2e/vue-owl-ui/blob/0fa47179dceadfc43ec656a6bbfdfebf6227ab20/src/components/message/index.js#L68)):*
<details><summary><i>Previously, Dsweih (Desmond Hsu) wrote…</i></summary><blockquote>

不知道有這個event耶，學習了
</blockquote></details>

`const ev = new AnimationEvent('animationend')` 
test裡產生不了這個eventQQ

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/163)*

**Comment by rwu823** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[src/components/message/index.js, line 60 at r2](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/163#-Khz26r4QnIEvwwAjXTI:-KhzKMPQs06brI-laCvS:bv2rhn4) ([raw file](https://github.com/cepave-f2e/vue-owl-ui/blob/0fa47179dceadfc43ec656a6bbfdfebf6227ab20/src/components/message/index.js#L60)):*
<details><summary><i>Previously, Dsweih (Desmond Hsu) wrote…</i></summary><blockquote>

this.$destroy() 是移除 vnode
this.$el.remove() 是移除 dom 上的 node
</blockquote></details>

OK, 那就改用 Kelly 講的方法來移除支援比較全面沒錯，`this.$el.parentNode.removeChild(this.$el)`

http://caniuse.com/#feat=childnode-remove

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/163)*

**Comment by rwu823** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[src/components/message/index.js, line 68 at r2](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/163#-KhvV_5Wo72KpeKKkQ2r:-KhzL9nsH287gIJ6nQjE:bghknlk) ([raw file](https://github.com/cepave-f2e/vue-owl-ui/blob/0fa47179dceadfc43ec656a6bbfdfebf6227ab20/src/components/message/index.js#L68)):*
<details><summary><i>Previously, CApopsicle (Kelly Su) wrote…</i></summary><blockquote>

`const ev = new AnimationEvent('animationend')` 
test裡產生不了這個eventQQ
</blockquote></details>

這邊應該不需要產生這個 event ？換了 class 就會進去 listener 了 QQ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/163)*

**Comment by desmond9319** [comment]
*[src/components/message/index.js, line 60 at r2](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/163#-Khz26r4QnIEvwwAjXTI:-KhzRuo-IqLcqLkWsk2I:b-896fix) ([raw file](https://github.com/cepave-f2e/vue-owl-ui/blob/0fa47179dceadfc43ec656a6bbfdfebf6227ab20/src/components/message/index.js#L60)):*
<details><summary><i>Previously, rwu823 (Rocky Wu) wrote…</i></summary><blockquote>

OK, 那就改用 Kelly 講的方法來移除支援比較全面沒錯，`this.$el.parentNode.removeChild(this.$el)`

http://caniuse.com/#feat=childnode-remove
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/163)*

**Comment by desmond9319** [comment]
*[src/components/message/message.scss, line 36 at r2](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/163#-KhyxPyVNHQKvbU0OlnN:-KhzSGT0B4k99z8ucY4o:b-886gsx) ([raw file](https://github.com/cepave-f2e/vue-owl-ui/blob/0fa47179dceadfc43ec656a6bbfdfebf6227ab20/src/components/message/message.scss#L36)):*
<details><summary><i>Previously, rwu823 (Rocky Wu) wrote…</i></summary><blockquote>

單層 selector 
</blockquote></details>

Fixed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/163)*

**Comment by chuanxd** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[src/components/message/index.js, line 104 at r1](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/163#-Khub68sshWUnMF-0P5f:-KhzcXCfnR1lESdcpxIz:bakv80l) ([raw file](https://github.com/cepave-f2e/vue-owl-ui/blob/7f6bd17381c6156c9985396f29737ff384c56f70/src/components/message/index.js#L104)):*
<details><summary><i>Previously, Dsweih (Desmond Hsu) wrote…</i></summary><blockquote>

知道了！
</blockquote></details>

html5 `<i>` 標準應該是不能  `self-close` ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/163)*

**Comment by desmond9319** [comment]
*[src/components/message/index.js, line 104 at r1](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/163#-Khub68sshWUnMF-0P5f:-KhzkQancCyM1KffUw6l:bjnwz5e) ([raw file](https://github.com/cepave-f2e/vue-owl-ui/blob/7f6bd17381c6156c9985396f29737ff384c56f70/src/components/message/index.js#L104)):*
<details><summary><i>Previously, chuanxd (Timmy Chang) wrote…</i></summary><blockquote>

html5 `<i>` 標準應該是不能  `self-close` ?
</blockquote></details>

對耶，根據 HTML5 spec，只有 `area`, `base`, `br`, `col`, `embed`, `hr`, `img`, `input`, `keygen`, `link`, `meta`, `param`, `source`, `track`, `wbr` 這些 tag 是 self-closing
雖然瀏覽器會忽略這樣的錯誤，但當 tag 後有其他 tag 時有可能會出現問題

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/163)*

**Comment by rwu823** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---

*[src/components/message/index.js, line 104 at r1](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/163#-Khub68sshWUnMF-0P5f:-Ki-1j6BwpNR03e8I0Lt:bx50q1p) ([raw file](https://github.com/cepave-f2e/vue-owl-ui/blob/7f6bd17381c6156c9985396f29737ff384c56f70/src/components/message/index.js#L104)):*
<details><summary><i>Previously, Dsweih (Desmond Hsu) wrote…</i></summary><blockquote>

對耶，根據 HTML5 spec，只有 `area`, `base`, `br`, `col`, `embed`, `hr`, `img`, `input`, `keygen`, `link`, `meta`, `param`, `source`, `track`, `wbr` 這些 tag 是 self-closing
雖然瀏覽器會忽略這樣的錯誤，但當 tag 後有其他 tag 時有可能會出現問題
</blockquote></details>

@chuanxd  這邊是 jsx 用法，應該不影響唷 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/163)*

**Comment by chuanxd** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[src/components/message/index.js, line 104 at r1](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/163#-Khub68sshWUnMF-0P5f:-Ki-HAnD_E4MT5oYBgsz:bb6ywmx) ([raw file](https://github.com/cepave-f2e/vue-owl-ui/blob/7f6bd17381c6156c9985396f29737ff384c56f70/src/components/message/index.js#L104)):*
<details><summary><i>Previously, rwu823 (Rocky Wu) wrote…</i></summary><blockquote>

@chuanxd  這邊是 jsx 用法，應該不影響唷 
</blockquote></details>

LGTM

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/163)*

**Comment by rwu823** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[src/components/message/index.js, line 63 at r3](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/163#-Ki2aaF0nEOtFD5QRmzR:-Ki2aaF0nEOtFD5QRmzS:b-cv9vct) ([raw file](https://github.com/cepave-f2e/vue-owl-ui/blob/0cfa9e57aec6cd75bfd560a6222a2442e8876dfb/src/components/message/index.js#L63)):*
> ```JavaScript
>       this.$el.parentNode.removeChild(this.$el)
>     } else {
>       this.$el.remove
> ```

`this.$el.remove()`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/163)*

**Comment by desmond9319** [comment]
*[src/components/message/index.js, line 63 at r3](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/163#-Ki2aaF0nEOtFD5QRmzR:-Ki2wYCXxy5NW37fUZrP:bt2vr1b) ([raw file](https://github.com/cepave-f2e/vue-owl-ui/blob/0cfa9e57aec6cd75bfd560a6222a2442e8876dfb/src/components/message/index.js#L63)):*
<details><summary><i>Previously, rwu823 (Rocky Wu) wrote…</i></summary><blockquote>

`this.$el.remove()`
</blockquote></details>

Fixed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/163)*

**Comment by rwu823** [comment]
Reviewed 3 of 3 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[src/components/message/message.scss, line 38 at r4](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/163#-Ki3pFqRuv3SSOnftI1x:-Ki3pFqRuv3SSOnftI1y:b-n0a6ql) ([raw file](https://github.com/cepave-f2e/vue-owl-ui/blob/bc4487381802458ad1ca4a10651e886fb2c19958/src/components/message/message.scss#L38)):*
> ```SCSS
>     .customIcon {
>       margin-right: 8px;
>     }
> ```

不放第一層的原因是 QQ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/163)*

**Comment by desmond9319** [comment]
*[src/components/message/message.scss, line 38 at r4](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/163#-Ki3pFqRuv3SSOnftI1x:-Ki3rmNn7WZxQek3RZ0Y:bdxl88n) ([raw file](https://github.com/cepave-f2e/vue-owl-ui/blob/bc4487381802458ad1ca4a10651e886fb2c19958/src/components/message/message.scss#L38)):*
<details><summary><i>Previously, rwu823 (Rocky Wu) wrote…</i></summary><blockquote>

不放第一層的原因是 QQ?
</blockquote></details>

疑，我改了耶＠＠
重推一次好了

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/163)*

**Comment by chuanxd** [comment]
Review status: 4 of 7 files reviewed at latest revision, 5 unresolved discussions, some commit checks broke.

---

*[src/components/message/message.scss, line 90 at r4](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/163#-Ki8D4chvgenqT8KVbTL:-Ki8D4chvgenqT8KVbTM:b-ur108w) ([raw file](https://github.com/cepave-f2e/vue-owl-ui/blob/bc4487381802458ad1ca4a10651e886fb2c19958/src/components/message/message.scss#L90)):*
> ```SCSS
> 
> .primary {
>   @include color-fill(var(--OWL-UI-COLOR-PRIMARY),#fff);
> ```

style lint ? prefer put space after comma

---

*[src/components/message/message.scss, line 94 at r4](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/163#-Ki8EEjnbsFBe9piyik8:-Ki8EEjnbsFBe9piyik9:bm8t5sl) ([raw file](https://github.com/cepave-f2e/vue-owl-ui/blob/bc4487381802458ad1ca4a10651e886fb2c19958/src/components/message/message.scss#L94)):*
> ```SCSS
> 
> .error {
>   @include color-fill(#e6175c,#fff);
> ```

CSS variables

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/163)*

**Comment by CApopsicle** [comment]
Review status: 4 of 7 files reviewed at latest revision, 5 unresolved discussions, some commit checks broke.

---

*[src/components/message/message.scss, line 94 at r4](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/163#-Ki8EEjnbsFBe9piyik8:-Ki8Ii7NcX5Zqq8jwpsQ:b-i2hzal) ([raw file](https://github.com/cepave-f2e/vue-owl-ui/blob/bc4487381802458ad1ca4a10651e886fb2c19958/src/components/message/message.scss#L94)):*
<details><summary><i>Previously, chuanxd (Timmy Chang) wrote…</i></summary><blockquote>

CSS variables
</blockquote></details>

`owl-ui` 只有
`primary`, `primary-light`, `primary-dark` 三個變數而已QQ 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/163)*

**Comment by chuanxd** [comment]
Review status: 4 of 7 files reviewed at latest revision, 5 unresolved discussions, some commit checks broke.

---

*[src/components/message/message.scss, line 94 at r4](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/163#-Ki8EEjnbsFBe9piyik8:-Ki8Kd3MxamTMGybZjxK:b2nhmf9) ([raw file](https://github.com/cepave-f2e/vue-owl-ui/blob/bc4487381802458ad1ca4a10651e886fb2c19958/src/components/message/message.scss#L94)):*
<details><summary><i>Previously, CApopsicle (Kelly Su) wrote…</i></summary><blockquote>

`owl-ui` 只有
`primary`, `primary-light`, `primary-dark` 三個變數而已QQ 
</blockquote></details>

QQ

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/163)*

**Comment by rwu823** [comment]
Reviewed 3 of 3 files at r5.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/163)*

**Pull request merged**
