### PR TITLE
[Input] Added `defaultValue` and `setValue` for Input

### PR DESCRIPTION
**Pull request by rwu823**
This change is [Reviewable](https://reviewable.io/reviews/cepave-f2e/vue-owl-ui/153)

### CODE REVIEW

**Comment by CApopsicle** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/components/input/__test__/input.spec.js, line 80 at r1](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/153#-Kfz59gguWr40E__nA4i:-Kfz59gguWr40E__nA4j:b-hoy9vg) ([raw file](https://github.com/cepave-f2e/vue-owl-ui/blob/c2019e7641088826ce9d6cb1f87c39dce9a372fb/src/components/input/__test__/input.spec.js#L80)):*
> ```JavaScript
> 
>   expect('owl').toBe(vm.value)
> ```

這邊寫相反也沒關係嗎
`expect(vm.value).toBe('owl')` 應該都是用 ` ===` 去check?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/153)*

**Comment by CApopsicle** [comment]
Reviewed 2 of 3 files at r1.
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/153)*

**Comment by CApopsicle** [comment]
Reviewed 1 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/153)*

**Comment by CApopsicle** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/153#-:-KfzAHMxRroNOaLXJOb7:bnfp4nl)*

**Comment by rwu823** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/components/input/__test__/input.spec.js, line 80 at r1](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/153#-Kfz59gguWr40E__nA4i:-KfzAJ6oxe5idQa74Tjk:b2nign6) ([raw file](https://github.com/cepave-f2e/vue-owl-ui/blob/c2019e7641088826ce9d6cb1f87c39dce9a372fb/src/components/input/__test__/input.spec.js#L80)):*
<details><summary><i>Previously, CApopsicle (Kelly Su) wrote…</i></summary><blockquote>

這邊寫相反也沒關係嗎
`expect(vm.value).toBe('owl')` 應該都是用 ` ===` 去check?
</blockquote></details>

yes

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/153)*

**Pull request merged**
