### PR TITLE
[ComplexQuery] Component

### PR DESCRIPTION
**Pull request by rwu823**
- [x] doc
- [x] component
- [x] test sepc

complexquery

---
This change is [Reviewable](https://reviewable.io/reviews/cepave-f2e/vue-owl-ui/141)

### CODE REVIEW

**Comment by desmond9319** [comment]
Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/141)*

**Comment by CApopsicle** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/client/views/complex-query/index.js, line 80 at r1](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/141#-Kf5r3fx9tZyekNGDhDs:-Kf5r3fyiB8IEZHmfonG:b-wgwcvk) ([raw file](https://github.com/cepave-f2e/vue-owl-ui/blob/322aae38e1ca498cfe1bb167aa8bf23571ccb7c2/src/client/views/complex-query/index.js#L80)):*
> ```JavaScript
>           <cdoe>
>             data: {JSON.stringify(outs, null, 2)}
>           </cdoe>
> ```

`<code>` QQ

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/141)*

**Comment by rwu823** [comment]
Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/client/views/complex-query/index.js, line 80 at r1](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/141#-Kf5r3fx9tZyekNGDhDs:-Kf5rGiHDsFpaUIz6m2c:burx0un) ([raw file](https://github.com/cepave-f2e/vue-owl-ui/blob/322aae38e1ca498cfe1bb167aa8bf23571ccb7c2/src/client/views/complex-query/index.js#L80)):*
<details><summary><i>Previously, CApopsicle (Kelly Su) wrote…</i></summary><blockquote>

`<code>` QQ
</blockquote></details>

good catch XD

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/141)*

**Comment by rwu823** [comment]
Review status: 8 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/client/views/complex-query/index.js, line 80 at r1](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/141#-Kf5r3fx9tZyekNGDhDs:-Kf9X_CRyY3kesx8TTJM:b-lx4fv5) ([raw file](https://github.com/cepave-f2e/vue-owl-ui/blob/322aae38e1ca498cfe1bb167aa8bf23571ccb7c2/src/client/views/complex-query/index.js#L80)):*
<details><summary><i>Previously, rwu823 (Rocky Wu) wrote…</i></summary><blockquote>

good catch XD
</blockquote></details>

Fixed  

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/141)*

**Comment by desmond9319** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/141)*

**Comment by CApopsicle** [comment]
右下角和左上角的資訊不一致耶 QQ 

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/141#-:-KfAPziyDHnofqEAUpk7:brs0dvr)*

**Comment by rwu823** [comment]
@capopsicle 
這個組件需求功能是這樣的，左上角的資訊會一直保留並累加每一次的選擇，右下只是針下當次的 XD

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/141#-:-KfARNGX4EQeU5XoAs6e:b-xn2bx7)*

**Comment by CApopsicle** [comment]
Reviewed 6 of 9 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/141)*

**Comment by CApopsicle** [comment]
這邊好像漏掉了向右的箭頭耶

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/141#-:-KfAiDn70OzPL26Ae6ek:b6c6b86)*

**Comment by rwu823** [comment]
@capopsicle 
經與設計討論過後，設備都攤平現在只有一層 @@

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/141#-:-KfAiqVP00voDBJk2Kw-:b6gmwaa)*

**Comment by CApopsicle** [comment]
:ok: :lgtm: 

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/141#-:-KfAj2gHxHIZQOHpFE5J:b-oggks3)*

**Comment by CApopsicle** [comment]
Reviewed 1 of 9 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/141)*

**Comment by CApopsicle** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/client/views/complex-query/index.js, line 80 at r1](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/141#-Kf5r3fx9tZyekNGDhDs:-KfAjdfejg8ntbDtLG2a:bg7igkv) ([raw file](https://github.com/cepave-f2e/vue-owl-ui/blob/322aae38e1ca498cfe1bb167aa8bf23571ccb7c2/src/client/views/complex-query/index.js#L80)):*
<details><summary><i>Previously, rwu823 (Rocky Wu) wrote…</i></summary><blockquote>

Fixed  
</blockquote></details>

:lgtm: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/141)*

**Pull request merged**
