### PR TITLE
[Icon] Add new icons

### PR DESCRIPTION
**Pull request by desmond9319**
利用旋轉 `arrow-down` icon 新增 `arrow-left` 與 `arrow-right` icons

---
This change is [Reviewable](https://reviewable.io/reviews/cepave-f2e/vue-owl-ui/140)

### CODE REVIEW

**Comment by rwu823** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/140#-KelpYW5TmqDBlL-VlZW:-KelpYW5TmqDBlL-VlZX:b-hti4l7) (no related file):*
<Icon /> component 沒改到

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/140)*

**Comment by chuanxd** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/140#-KelsWVxuz8QqzAx9rKJ:-KelsWVxuz8QqzAx9rKK:bshfe6x) (no related file):*
first blood :1st_place_medal: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/140)*

**Comment by desmond9319** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/140#-KelpYW5TmqDBlL-VlZW:-KemNefqiOjnV-Z7xdFW:b-qsseby) (no related file):*
<details><summary><i>Previously, rwu823 (Rocky Wu) wrote…</i></summary><blockquote>

<Icon /> component 沒改到
</blockquote></details>

fixed!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/140)*

**Comment by rwu823** [comment]
Review status: 0 of 4 files reviewed at latest revision, 5 unresolved discussions.

---

*[src/client/views/icons/icon.scss, line 10 at r1](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/140#-KeprHND7hBF8HF3CrTQ:-KeprHND7hBF8HF3CrTR:b-4a8nsz) ([raw file](https://github.com/cepave-f2e/vue-owl-ui/blob/23241744d7dcd9c850b6908fc8b10ff34cc2ec91/src/client/views/icons/icon.scss#L10)):*
> ```SCSS
>     margin: 0;
>   }
> }
> ```

這隻檔案不該有被動到

---

*[src/components/icon/index.js, line 39 at r1](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/140#-KepqpaI0aWizP_18mHn:-KepqpaJU2cfSAUkNoFI:bo3laxs) ([raw file](https://github.com/cepave-f2e/vue-owl-ui/blob/23241744d7dcd9c850b6908fc8b10ff34cc2ec91/src/components/icon/index.js#L39)):*
> ```JavaScript
>   render(h) {
>     const { typ, cSize } = this
>     
> ```

怎麼多了`....`？

---

*[src/components/icon/index.js, line 48 at r1](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/140#-Keprug62fooOxe_oCB_:-Keprug62fooOxe_oCBa:b-jnx49k) ([raw file](https://github.com/cepave-f2e/vue-owl-ui/blob/23241744d7dcd9c850b6908fc8b10ff34cc2ec91/src/components/icon/index.js#L48)):*
> ```JavaScript
>          `<use xlink:href="#owl-icons-${(typ === 'arrow-left') || (typ === 'arrow-right') ? 'arrow-down' : typ}"></use>` 
>       } />
>       
> ```

這邊也是看是否編輯器設定有問題，不該多這些額外的字元

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/140)*

**Comment by rwu823** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/140)*

**Comment by desmond9319** [comment]
*[src/client/views/icons/icon.scss, line 10 at r1](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/140#-KeprHND7hBF8HF3CrTQ:-KepyA8WOJGM0mJ39lLb:b-q4idoz) ([raw file](https://github.com/cepave-f2e/vue-owl-ui/blob/23241744d7dcd9c850b6908fc8b10ff34cc2ec91/src/client/views/icons/icon.scss#L10)):*
<details><summary><i>Previously, rwu823 (Rocky Wu) wrote…</i></summary><blockquote>

這隻檔案不該有被動到
</blockquote></details>

我後來有把改動的地方刪掉了，不知道為什麼它偵測有改動


---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/140)*

**Comment by desmond9319** [comment]
*[src/components/icon/index.js, line 48 at r1](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/140#-Keprug62fooOxe_oCB_:-Keq53VLt9wXIxPcDjRG:bloo8wz) ([raw file](https://github.com/cepave-f2e/vue-owl-ui/blob/23241744d7dcd9c850b6908fc8b10ff34cc2ec91/src/components/icon/index.js#L48)):*
<details><summary><i>Previously, rwu823 (Rocky Wu) wrote…</i></summary><blockquote>

這邊也是看是否編輯器設定有問題，不該多這些額外的字元
</blockquote></details>

修正好了

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/140)*

**Comment by desmond9319** [comment]
*[src/components/icon/index.js, line 39 at r1](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/140#-KepqpaI0aWizP_18mHn:-Keq50MaRa-YluMYBYR6:bloo8wz) ([raw file](https://github.com/cepave-f2e/vue-owl-ui/blob/23241744d7dcd9c850b6908fc8b10ff34cc2ec91/src/components/icon/index.js#L39)):*
<details><summary><i>Previously, rwu823 (Rocky Wu) wrote…</i></summary><blockquote>

怎麼多了`....`？
</blockquote></details>

修正好了

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/140)*

**Comment by chuanxd** [comment]
Review status: 3 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/client/views/icons/icon.scss, line 10 at r1](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/140#-KeprHND7hBF8HF3CrTQ:-KeqG4s1E52IVTerc4lh:b-2co3ex) ([raw file](https://github.com/cepave-f2e/vue-owl-ui/blob/23241744d7dcd9c850b6908fc8b10ff34cc2ec91/src/client/views/icons/icon.scss#L10)):*
<details><summary><i>Previously, Dsweih (Desmond Hsu) wrote…</i></summary><blockquote>

我後來有把改動的地方刪掉了，不知道為什麼它偵測有改動


</blockquote></details>

直接把檔案 reset

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/140)*

**Comment by rwu823** [comment]
Reviewed 2 of 2 files at r2.
Review status: 1 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/client/views/icons/index.js, line 9 at r3](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/140#-Kf5Tl5ZvChox3lGd3fP:-Kf5Tl5ZvChox3lGd3fQ:b2c95yp) ([raw file](https://github.com/cepave-f2e/vue-owl-ui/blob/4a59e2db8bdec566a35fd56a68d223956701395c/src/client/views/icons/index.js#L9)):*
> ```JavaScript
> })
> 
> icons = ['owl-icons-arrow-left', 'owl-icons-arrow-right'].concat(icons)
> ```

`icons = ['owl-icons-arrow-left', 'owl-icons-arrow-right', ...icons]`

---

*[src/components/icon/index.js, line 42 at r3](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/140#-Kf5UTNarhVHtxakOpEl:-Kf5UTNarhVHtxakOpEm:bnq7dko) ([raw file](https://github.com/cepave-f2e/vue-owl-ui/blob/4a59e2db8bdec566a35fd56a68d223956701395c/src/components/icon/index.js#L42)):*
> ```JavaScript
>     rotate() {
>       const { typ } = this
>       return direction[typ] ? direction[typ] : typ
> ```

`return direction[typ] || typ`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/140)*

**Comment by rwu823** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[src/client/views/icons/icon.scss, line 10 at r1](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/140#-KeprHND7hBF8HF3CrTQ:-Kf5UsmEo6lqt5hK8Thr:b-ctvteb) ([raw file](https://github.com/cepave-f2e/vue-owl-ui/blob/23241744d7dcd9c850b6908fc8b10ff34cc2ec91/src/client/views/icons/icon.scss#L10)):*
<details><summary><i>Previously, chuanxd (Timmy Chang) wrote…</i></summary><blockquote>

直接把檔案 reset
</blockquote></details>

這隻還是有進到版控裡

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/140)*

**Comment by desmond9319** [comment]
*[src/client/views/icons/icon.scss, line 10 at r1](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/140#-KeprHND7hBF8HF3CrTQ:-Kf5YkzkTvLfvWcsz40U:bvio9ua) ([raw file](https://github.com/cepave-f2e/vue-owl-ui/blob/23241744d7dcd9c850b6908fc8b10ff34cc2ec91/src/client/views/icons/icon.scss#L10)):*
<details><summary><i>Previously, rwu823 (Rocky Wu) wrote…</i></summary><blockquote>

這隻還是有進到版控裡
</blockquote></details>

我從 github 的 files change 看沒有耶
只有 reviewable 有顯示？

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/140)*

**Comment by rwu823** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/140)*

**Pull request merged**
