### PR TITLE
<DatePicker> and <TimePicker>

### PR DESCRIPTION
**Pull request by rwu823**
## DatePicker

date-picker

## TimePicker

timepicker

---
This change is [Reviewable](https://reviewable.io/reviews/cepave-f2e/vue-owl-ui/129)

### CODE REVIEW

**Comment by rwu823** [comment]
#  DatePicker



# TimePicker

timepicker

---

Review status: 0 of 22 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/129#-:-Ke87SIE-zOELHfvAwOj:b-fjoqvc)*

**Comment by rwu823** [comment]
Review status: 0 of 22 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/129#-KeI9O5AgTzzzRwlA1qU:-KeI9O5AgTzzzRwlA1qV:bb7p34n) (no related file):*
test

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/129)*

**Comment by CApopsicle** [comment]
Review status: 0 of 22 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/129#-KeI9O5AgTzzzRwlA1qU:-KeI9efXrkb83G2VX4qG:b-qsseby) (no related file):*
<details><summary><i>Previously, rwu823 (Rocky Wu) wrote…</i></summary><blockquote>

test
</blockquote></details>

fixed!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/129)*

**Comment by CApopsicle** [comment]
Reviewed 1 of 19 files at r1, 2 of 2 files at r2, 2 of 9 files at r4.
Review status: 5 of 22 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/129)*

**Comment by CApopsicle** [comment]
Reviewed 1 of 19 files at r1, 1 of 9 files at r4, 1 of 3 files at r5.
Review status: 7 of 22 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/components/date-picker/cal.js, line 12 at r5](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/129#-KeftLhe461Faxp6uN_6:-KeftLhe461Faxp6uN_7:b-425hbn) ([raw file](https://github.com/cepave-f2e/vue-owl-ui/blob/cc8d60491faf6910efbca64b96d8af6d88b0567e/src/components/date-picker/cal.js#L12)):*
> ```JavaScript
>     yearMonth: {
>       type: Array,
>       require: true,
> ```

`required` ? 
應該 `required` 和 `default` 寫一個就好(?

---

*[src/components/date-picker/index.js, line 11 at r5](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/129#-KefsqL6j3L_mUYrc48s:-KefsqL6j3L_mUYrc48t:b-425hbn) ([raw file](https://github.com/cepave-f2e/vue-owl-ui/blob/cc8d60491faf6910efbca64b96d8af6d88b0567e/src/components/date-picker/index.js#L11)):*
> ```JavaScript
>     yearMonth: {
>       type: Array,
>       require: true,
> ```

`required` ? 
應該 `required` 和 `default` 寫一個就好(?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/129)*

**Comment by rwu823** [comment]
Review status: 7 of 22 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/components/date-picker/cal.js, line 12 at r5](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/129#-KeftLhe461Faxp6uN_6:-KefyccokP2jJUsW6bY3:b-8fx2u7) ([raw file](https://github.com/cepave-f2e/vue-owl-ui/blob/cc8d60491faf6910efbca64b96d8af6d88b0567e/src/components/date-picker/cal.js#L12)):*
<details><summary><i>Previously, CApopsicle (Kelly Su) wrote…</i></summary><blockquote>

`required` ? 
應該 `required` 和 `default` 寫一個就好(?
</blockquote></details>

:+1: 

---

*[src/components/date-picker/index.js, line 11 at r5](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/129#-KefsqL6j3L_mUYrc48s:-KefyZ13rFE7pKeBQU44:b-8fx2u7) ([raw file](https://github.com/cepave-f2e/vue-owl-ui/blob/cc8d60491faf6910efbca64b96d8af6d88b0567e/src/components/date-picker/index.js#L11)):*
<details><summary><i>Previously, CApopsicle (Kelly Su) wrote…</i></summary><blockquote>

`required` ? 
應該 `required` 和 `default` 寫一個就好(?
</blockquote></details>

:+1: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/129)*

**Comment by desmond9319** [comment]
*[src/client/views/date-picker/index.js, line 18 at r5](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/129#-Kf5dlGbHEJQ8u2CK5vn:-Kf5dlGbHEJQ8u2CK5vo:b-4ohz1t) ([raw file](https://github.com/cepave-f2e/vue-owl-ui/blob/cc8d60491faf6910efbca64b96d8af6d88b0567e/src/client/views/date-picker/index.js#L18)):*
> ```JavaScript
>   },
>   render(h) {
>     const { $slots, outs, onPick } = this
> ```

$slots 沒用到？

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/129)*

**Comment by rwu823** [comment]
Review status: 4 of 22 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/client/views/date-picker/index.js, line 18 at r5](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/129#-Kf5dlGbHEJQ8u2CK5vn:-Kf5eu8P48ro6bgzO9I5:b-7ql1td) ([raw file](https://github.com/cepave-f2e/vue-owl-ui/blob/cc8d60491faf6910efbca64b96d8af6d88b0567e/src/client/views/date-picker/index.js#L18)):*
<details><summary><i>Previously, Dsweih (Desmond Hsu) wrote…</i></summary><blockquote>

$slots 沒用到？
</blockquote></details>

fixed

---

*[src/components/date-picker/cal.js, line 12 at r5](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/129#-KeftLhe461Faxp6uN_6:-Kf5e4XajlEfBTLRWmY0:b-7ql1td) ([raw file](https://github.com/cepave-f2e/vue-owl-ui/blob/cc8d60491faf6910efbca64b96d8af6d88b0567e/src/components/date-picker/cal.js#L12)):*
<details><summary><i>Previously, rwu823 (Rocky Wu) wrote…</i></summary><blockquote>

:+1: 
</blockquote></details>

fixed

---

*[src/components/date-picker/index.js, line 11 at r5](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/129#-KefsqL6j3L_mUYrc48s:-Kf5exNXkKAl_9ZUmOHJ:b-7ql1td) ([raw file](https://github.com/cepave-f2e/vue-owl-ui/blob/cc8d60491faf6910efbca64b96d8af6d88b0567e/src/components/date-picker/index.js#L11)):*
<details><summary><i>Previously, rwu823 (Rocky Wu) wrote…</i></summary><blockquote>

:+1: 
</blockquote></details>

fixed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/129)*

**Comment by desmond9319** [comment]
*[src/client/views/time-picker/index.js, line 24 at r5](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/129#-Kf5gKmIJqsEHZyL_noY:-Kf5gKmIJqsEHZyL_noZ:brx3yd5) ([raw file](https://github.com/cepave-f2e/vue-owl-ui/blob/cc8d60491faf6910efbca64b96d8af6d88b0567e/src/client/views/time-picker/index.js#L24)):*
> ```JavaScript
>   },
>   render(h) {
>     const { $slots, onChange, outs } = this
> ```

$slots :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/129)*

**Comment by CApopsicle** [comment]
Reviewed 2 of 19 files at r1, 2 of 4 files at r3, 1 of 9 files at r4, 1 of 3 files at r5.
Review status: 10 of 22 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/components/time-picker/index.js, line 103 at r5](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/129#-Kf5elqpsnNqLkJR-XrR:-Kf5elqpsnNqLkJR-XrS:byzp3ht) ([raw file](https://github.com/cepave-f2e/vue-owl-ui/blob/cc8d60491faf6910efbca64b96d8af6d88b0567e/src/components/time-picker/index.js#L103)):*
> ```JavaScript
>           startMin = 0
>           startHour += 1
>         }
> ```


這邊 `start="00:05", end="23:59"` 超過 `01:00` 之後會變成 15, 30, 45, 00

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/129)*

**Comment by rwu823** [comment]
Review status: 10 of 22 files reviewed at latest revision, 3 unresolved discussions.

---

*[src/components/time-picker/index.js, line 103 at r5](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/129#-Kf5elqpsnNqLkJR-XrR:-Kf5j2oCuOhwYfGLfGF0:bm85ht8) ([raw file](https://github.com/cepave-f2e/vue-owl-ui/blob/cc8d60491faf6910efbca64b96d8af6d88b0567e/src/components/time-picker/index.js#L103)):*
<details><summary><i>Previously, CApopsicle (Kelly Su) wrote…</i></summary><blockquote>


這邊 `start="00:05", end="23:59"` 超過 `01:00` 之後會變成 15, 30, 45, 00
</blockquote></details>

 :scream:

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/129)*

**Comment by CApopsicle** [comment]
Reviewed 2 of 19 files at r1, 1 of 4 files at r3, 1 of 9 files at r4, 1 of 3 files at r5, 2 of 3 files at r6.
Review status: 17 of 22 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/client/views/date-picker/doc.md, line 9 at r5](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/129#-Kf5lqh8ckM7H0vWAtfX:-Kf5lqh8ckM7H0vWAtfY:bw9an36) ([raw file](https://github.com/cepave-f2e/vue-owl-ui/blob/cc8d60491faf6910efbca64b96d8af6d88b0567e/src/client/views/date-picker/doc.md#L9)):*
> ```Markdown
>   type: Array,
>   require: true,
>   default: () => [(new Date).getFullYear(), (new Date).getMonth() + 1]
> ```

這邊 QQ `required` 和 `default`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/129)*

**Comment by CApopsicle** [comment]
Reviewed 1 of 19 files at r1, 1 of 9 files at r4.
Review status: 19 of 22 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/129)*

**Comment by rwu823** [comment]
Review status: 19 of 22 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/client/views/date-picker/doc.md, line 9 at r5](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/129#-Kf5lqh8ckM7H0vWAtfX:-Kf9ZjWwNl-yotzilZvr:b-7ql1td) ([raw file](https://github.com/cepave-f2e/vue-owl-ui/blob/cc8d60491faf6910efbca64b96d8af6d88b0567e/src/client/views/date-picker/doc.md#L9)):*
<details><summary><i>Previously, CApopsicle (Kelly Su) wrote…</i></summary><blockquote>

這邊 QQ `required` 和 `default`
</blockquote></details>

fixed

---

*[src/client/views/time-picker/index.js, line 24 at r5](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/129#-Kf5gKmIJqsEHZyL_noY:-Kf9ZmHLLm8uygTwX4Md:b-7ql1td) ([raw file](https://github.com/cepave-f2e/vue-owl-ui/blob/cc8d60491faf6910efbca64b96d8af6d88b0567e/src/client/views/time-picker/index.js#L24)):*
<details><summary><i>Previously, Dsweih (Desmond Hsu) wrote…</i></summary><blockquote>

$slots :)
</blockquote></details>

fixed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/129)*

**Comment by rwu823** [comment]
Review status: 18 of 22 files reviewed at latest revision, 4 unresolved discussions.

---

*[src/components/time-picker/index.js, line 103 at r5](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/129#-Kf5elqpsnNqLkJR-XrR:-Kf9isbl_De9i72JIBMf:b-886gsx) ([raw file](https://github.com/cepave-f2e/vue-owl-ui/blob/cc8d60491faf6910efbca64b96d8af6d88b0567e/src/components/time-picker/index.js#L103)):*
<details><summary><i>Previously, rwu823 (Rocky Wu) wrote…</i></summary><blockquote>

 :scream:
</blockquote></details>

Fixed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/129)*

**Comment by CApopsicle** [comment]
:lgtm:

---

Review status: 16 of 22 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/129#-:-KfAlV1SCrnYVb3zLeLk:bnfp4nl)*

**Comment by CApopsicle** [comment]
Reviewed 1 of 3 files at r6, 1 of 3 files at r7.
Review status: 18 of 22 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/129)*

**Comment by CApopsicle** [comment]
Reviewed 1 of 3 files at r7.
Review status: 19 of 22 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/129)*

**Comment by CApopsicle** [comment]
Reviewed 1 of 3 files at r7.
Review status: 20 of 22 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/129)*

**Comment by CApopsicle** [comment]
Reviewed 2 of 2 files at r8.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/129)*

**Comment by CApopsicle** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/client/views/date-picker/index.js, line 18 at r5](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/129#-Kf5dlGbHEJQ8u2CK5vn:-KfAlw8qG_TJeoFsPRFk:bg7igkv) ([raw file](https://github.com/cepave-f2e/vue-owl-ui/blob/cc8d60491faf6910efbca64b96d8af6d88b0567e/src/client/views/date-picker/index.js#L18)):*
<details><summary><i>Previously, rwu823 (Rocky Wu) wrote…</i></summary><blockquote>

fixed
</blockquote></details>

:lgtm: 

---

*[src/client/views/time-picker/index.js, line 24 at r5](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/129#-Kf5gKmIJqsEHZyL_noY:-KfAlykdIW0VeG23TcVj:bg7igkv) ([raw file](https://github.com/cepave-f2e/vue-owl-ui/blob/cc8d60491faf6910efbca64b96d8af6d88b0567e/src/client/views/time-picker/index.js#L24)):*
<details><summary><i>Previously, rwu823 (Rocky Wu) wrote…</i></summary><blockquote>

fixed
</blockquote></details>

:lgtm: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/129)*

**Pull request merged**
