### PR TITLE
[MultiSelect] watch dynamic-updated props `options`

### PR DESCRIPTION
**Pull request by CApopsicle**
- 使用的時候發現忘記讓 `options` 可以dynamic update了，補上
- 修改一些之前JJ建議的style

cc @rwu823 @Dsweih

---
This change is [Reviewable](https://reviewable.io/reviews/cepave-f2e/vue-owl-ui/144)

### CODE REVIEW

**Comment by rwu823** [comment]
Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[src/components/multi-select/index.js, line 71 at r1](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/144#-KfEQ26DudOovTZT2OM-:-KfEQ26F_-gt3AL1-83q:b8d3n0u) ([raw file](https://github.com/cepave-f2e/vue-owl-ui/blob/31e3fad24c508dbb7d598e88e50d9ea181b4359c/src/components/multi-select/index.js#L71)):*
> ```JavaScript
>   mounted() {
>     if (this.options.length) {
>       this.displayIdx = [...Array(this.options.length)].map((v, i) => {
> ```

`this.displayIdx = [...Array(this.options.length).keys()]`

---

*[src/components/multi-select/index.js, line 83 at r1](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/144#-KfEQ988WJ6DXj015BNe:-KfEQ988WJ6DXj015BNf:b8d3n0u) ([raw file](https://github.com/cepave-f2e/vue-owl-ui/blob/31e3fad24c508dbb7d598e88e50d9ea181b4359c/src/components/multi-select/index.js#L83)):*
> ```JavaScript
>   watch: {
>     options(newVal) {
>       this.displayIdx = [...Array(newVal.length)].map((v, i) => {
> ```

`this.displayIdx = [...Array(this.options.length).keys()]`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/144)*

**Comment by rwu823** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/144)*

**Comment by CApopsicle** [comment]
Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/components/multi-select/index.js, line 71 at r1](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/144#-KfEQ26DudOovTZT2OM-:-KfFAg8ufpnf6oURVWOC:b-7ql1td) ([raw file](https://github.com/cepave-f2e/vue-owl-ui/blob/31e3fad24c508dbb7d598e88e50d9ea181b4359c/src/components/multi-select/index.js#L71)):*
<details><summary><i>Previously, rwu823 (Rocky Wu) wrote…</i></summary><blockquote>

`this.displayIdx = [...Array(this.options.length).keys()]`
</blockquote></details>

fixed

---

*[src/components/multi-select/index.js, line 83 at r1](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/144#-KfEQ988WJ6DXj015BNe:-KfFAoL7-6cNbRJhOptA:b-7ql1td) ([raw file](https://github.com/cepave-f2e/vue-owl-ui/blob/31e3fad24c508dbb7d598e88e50d9ea181b4359c/src/components/multi-select/index.js#L83)):*
<details><summary><i>Previously, rwu823 (Rocky Wu) wrote…</i></summary><blockquote>

`this.displayIdx = [...Array(this.options.length).keys()]`
</blockquote></details>

fixed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/144)*

**Comment by rwu823** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/144)*

**Pull request merged**
