### PR TITLE
[Grid] Fix grid'css exports to global

### PR DESCRIPTION
**Pull request by rwu823**
@Dsweih 

image

- 如果把 `[attr]` 拉出去第一層，會變成 global 互相影響

---
This change is [Reviewable](https://reviewable.io/reviews/cepave-f2e/vue-owl-ui/161)

### CODE REVIEW

**Comment by desmond9319** [comment]
*[src/components/grid/grid.scss, line 24 at r1](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/161#-KgORwi7y-6FabsqtFPp:-KgORwi7y-6FabsqtFPq:bf2p09y) ([raw file](https://github.com/cepave-f2e/vue-owl-ui/blob/4aba389436005884a2d2de196e0a20b4440ed971/src/components/grid/grid.scss#L24)):*
> ```SCSS
>   }
>   [data-role="col"] {
>     position: relative;
> ```

這裡是要預設讓 col relative嗎？

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/161)*

**Comment by rwu823** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/components/grid/grid.scss, line 24 at r1](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/161#-KgORwi7y-6FabsqtFPp:-KgS11LWAHQ0jGVyvQoY:b-v9zwi6) ([raw file](https://github.com/cepave-f2e/vue-owl-ui/blob/4aba389436005884a2d2de196e0a20b4440ed971/src/components/grid/grid.scss#L24)):*
<details><summary><i>Previously, Dsweih (Desmond Hsu) wrote…</i></summary><blockquote>

這裡是要預設讓 col relative嗎？
</blockquote></details>

yes,  sort 的小箭頭定位會用位

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/161)*

**Comment by desmond9319** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/161)*

**Comment by desmond9319** [comment]
*[src/components/grid/grid.scss, line 24 at r1](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/161#-KgORwi7y-6FabsqtFPp:-KgSG47O__Qpq2nSKDr_:b32w0x) ([raw file](https://github.com/cepave-f2e/vue-owl-ui/blob/74f60ee865679a7cc700efa4f8a5a7119c6474c8/src/components/grid/grid.scss#L24)):*
<details><summary><i>Previously, rwu823 (Rocky Wu) wrote…</i></summary><blockquote>

yes,  sort 的小箭頭定位會用位
</blockquote></details>

OK

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/161)*

**Pull request merged**
