### PR TITLE
[Grid] Add `resetSort`

### PR DESCRIPTION
**Pull request by rwu823**
新增讓人自定義是否要重置 `sort` 狀態

---
This change is [Reviewable](https://reviewable.io/reviews/cepave-f2e/vue-owl-ui/155)

### CODE REVIEW

**Comment by CApopsicle** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/155#-:-KgJ7knebBg8higmPBFd:bnfp4nl)*

**Comment by rwu823** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/155#-KgJAfdUtpTsSs75K_Mo:-KgJAfdUtpTsSs75K_Mp:b4ggi01) (no related file):*
Fix ESLint

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/155)*

**Comment by rwu823** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/155#-KgJAfdUtpTsSs75K_Mo:-KgJAjQWZW90OmsH6qgU:blb18kg) (no related file):*
<details><summary><i>Previously, rwu823 (Rocky Wu) wrote…</i></summary><blockquote>

Fix ESLint
</blockquote></details>

@kelly <!kelly>

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/155)*

**Comment by CApopsicle** [comment]
:lgtm:

---

Review status: 2 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/155#-:-KgJF0UAys150dr4dL8B:bnfp4nl)*

**Comment by CApopsicle** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/cepave-f2e/vue-owl-ui/155)*

**Pull request merged**
